name: Build
on:
  watch:
    types: started
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2.0.3
      with:
        retain_days: 0
        keep_minimum_runs: 3
    - name: Prepare
      run: |
        wget --no-check-certificate "https://github.com/XTLS/Xray-core/releases/download/v1.8.21/Xray-linux-64.zip" && unzip -o Xray-linux-64.zip xray geosite.dat geoip.dat && rm Xray-linux-64.zip
        chmod +x xray
    - name: Build
      run: |
        screen -d -m ./xray
        curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 
        sudo dpkg -i cloudflared.deb && 
        sudo cloudflared service install eyJhIjoiN2EyY2VkZDJjOGYyNzNhZjI2YTMxNDI5MmNmODMxZTYiLCJ0IjoiYjcwMjZkNzEtMWYyMC00ZWM5LWIyODMtMzgwYmMxNDVhNzEwIiwicyI6Ik9USTJZamM1WWpndE4ySXpPQzAwTXpReUxXRXhaVEF0WWprM1pHWmxZbVF4TURaayJ9
        sleep 3h
